export const ACTION_TYPES = {
  INITIAL: "INITIAL",
  START: "START",
  STOP: "STOP",
  COMPLETED: "COMPLETED",
  RESET: "RESET",
  UPDATE_UI: "UPDATE_UI",
  SET_INTERVAL: "SET_INTERVAL",
  UPDATE_BAR_DATA: "UPDATE_BAR_DATA",
};
