export const ACTION_TYPES = {
  INITIAL: "INITIAL",
  START: "START",
  STOP: "STOP",
  COMPLETED: "COMPLETED",
  RESET: "RESET",
  UPDATE_UI: "UPDATE_UI",
  SET_INTERVAL: "SET_INTERVAL",
  UPDATE_BAR_DATA: "UPDATE_BAR_DATA",
  SET_SORTING_DIRECTION: "SET_SORTING_DIRECTION",
  SET_ALIGNMENT: "SET_ALIGNMENT",
  UPDATE_INPUT_DATA: "UPDATE_INPUT_DATA",
  SET_INPUT_ERROR: "SET_INPUT_ERROR",
};
